# Generated by Django 5.2.3 on 2025-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('party_address', models.CharField(blank=True, max_length=100, null=True)),
                ('tds_section', models.CharField(blank=True, choices=[('120a', '120a'), ('120b', '120b'), ('120c', '120c')], max_length=100, null=True)),
                ('tds_pct', models.FloatField(default=0)),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
